# Generated by Django 4.1.1 on 2022-10-12 23:08

import uuid

from django.apps import apps
from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_uuid"),
    ]

    def gen_uuid(apps, schema_editor):
        user = apps.get_model("accounts", "User")
        # Can just add uuid to User objs and it will cover both Student and Prof objects due to 1:1
        for row in user.objects.all():
            row.uuid = uuid.uuid4()
            row.save(update_fields=["uuid"])

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
