# Generated by Django 4.1.1 on 2022-10-03 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=60)),
                ("min_group_size", models.PositiveIntegerField()),
                ("max_group_size", models.PositiveIntegerField()),
                ("end_date", models.DateField()),
                ("description", models.CharField(max_length=200)),
            ],
        ),
    ]
