# Generated by Django 4.1.1 on 2022-10-03 04:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="prof",
            field=models.ManyToManyField(
                related_name="prof_projects", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="students",
            field=models.ManyToManyField(
                related_name="student_projects", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="end_date",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="max_group_size",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="project",
            name="min_group_size",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
