# Generated by Django 4.1.1 on 2022-10-03 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_student_professor"),
        ("projects", "0002_project_prof_project_students_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="prof",
            field=models.ManyToManyField(
                related_name="prof_projects", to="accounts.professor"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="students",
            field=models.ManyToManyField(
                related_name="student_projects", to="accounts.student"
            ),
        ),
    ]
