# Generated by Django 4.1.1 on 2022-10-04 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_student_professor"),
        ("projects", "0003_alter_project_prof_alter_project_students"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="prof",
        ),
        migrations.AddField(
            model_name="project",
            name="join_code",
            field=models.CharField(default=None, max_length=8, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="professor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prof_projects",
                to="accounts.professor",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="end_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="max_group_size",
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name="project",
            name="min_group_size",
            field=models.PositiveIntegerField(default=2),
        ),
    ]
