# Generated by Django 4.1.1 on 2022-10-11 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_student_professor"),
        ("projects", "0004_remove_project_prof_project_join_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.CharField(max_length=250)),
                ("skills", models.JSONField()),
                (
                    "year",
                    models.CharField(
                        choices=[
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("4+", "4+"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "pronouns",
                    models.CharField(
                        choices=[
                            ("he/him", "he/him"),
                            ("she/her", "she/her"),
                            ("they/them", "they/them"),
                            ("other", "other"),
                        ],
                        max_length=12,
                    ),
                ),
                ("contact_details", models.CharField(max_length=250)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.student",
                    ),
                ),
            ],
        ),
    ]
