# Generated by Django 4.1.1 on 2022-10-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_projectprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="join_code",
            field=models.CharField(default=None, max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="projectprofile",
            name="bio",
            field=models.CharField(max_length=375),
        ),
        migrations.AlterField(
            model_name="projectprofile",
            name="contact_details",
            field=models.CharField(max_length=375),
        ),
    ]
