# Generated by Django 4.1.1 on 2022-10-18 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_auto_20221012_2308"),
        ("projects", "0006_alter_project_join_code_alter_projectprofile_bio_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InteractionsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("operation", models.BooleanField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_interactions",
                        to="projects.project",
                    ),
                ),
                (
                    "swipee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="swipee",
                        to="accounts.student",
                    ),
                ),
                (
                    "swiper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="swiper",
                        to="accounts.student",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="interactionsmodel",
            constraint=models.UniqueConstraint(
                fields=("project", "swiper", "swipee"), name="unique interaction"
            ),
        ),
    ]
