# Generated by Django 4.1.1 on 2022-10-18 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_auto_20221012_2308"),
        ("projects", "0007_interactionsmodel_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="InteractionsModel",
            new_name="Interaction",
        ),
        migrations.RenameField(
            model_name="interaction",
            old_name="operation",
            new_name="liked",
        ),
    ]
