# Generated by Django 4.1.1 on 2022-10-25 02:59

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_auto_20221012_2308"),
        ("projects", "0008_rename_interactionsmodel_interaction_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group_name",
                    models.CharField(
                        blank=True, default=None, max_length=60, null=True, unique=True
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "candidates",
                    models.ManyToManyField(
                        related_name="group_candidates", to="accounts.student"
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        related_name="group_members", to="accounts.student"
                    ),
                ),
                (
                    "project_key",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project",
                        to="projects.project",
                    ),
                ),
                (
                    "rejects",
                    models.ManyToManyField(
                        related_name="group_rejects", to="accounts.student"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GroupInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("liked", models.BooleanField()),
                (
                    "likee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likee",
                        to="projects.group",
                    ),
                ),
                (
                    "liker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liker",
                        to="accounts.student",
                    ),
                ),
            ],
        ),
    ]
