# Generated by Django 4.1.1 on 2022-10-25 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0009_group_groupinteraction"),
    ]

    operations = [
        migrations.RenameField(
            model_name="group",
            old_name="project_key",
            new_name="project",
        ),
        migrations.AlterField(
            model_name="group",
            name="group_name",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddConstraint(
            model_name="group",
            constraint=models.UniqueConstraint(
                fields=("project", "group_name"), name="unique group"
            ),
        ),
        migrations.AddConstraint(
            model_name="groupinteraction",
            constraint=models.UniqueConstraint(
                fields=("liker", "likee"), name="unique group interaction"
            ),
        ),
    ]
