# Generated by Django 4.1.1 on 2022-10-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_auto_20221012_2308"),
        ("projects", "0010_rename_project_key_group_project_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="candidates",
            field=models.ManyToManyField(
                blank=True, related_name="group_candidates", to="accounts.student"
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="members",
            field=models.ManyToManyField(
                blank=True, related_name="group_members", to="accounts.student"
            ),
        ),
    ]
