# Generated by Django 4.1.1 on 2022-10-26 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_auto_20221012_2308"),
        ("projects", "0011_alter_group_candidates_alter_group_members"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="members",
            field=models.ManyToManyField(
                related_name="group_members", to="accounts.student"
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="rejects",
            field=models.ManyToManyField(
                blank=True, related_name="group_rejects", to="accounts.student"
            ),
        ),
    ]
