# Generated by Django 4.1.1 on 2022-10-28 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_auto_20221012_2308"),
        ("projects", "0012_alter_group_members_alter_group_rejects"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="candidates",
            field=models.ManyToManyField(
                blank=True, related_name="candidate_groups", to="accounts.student"
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="members",
            field=models.ManyToManyField(
                related_name="joined_groups", to="accounts.student"
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="rejects",
            field=models.ManyToManyField(
                blank=True, related_name="rejected_groups", to="accounts.student"
            ),
        ),
        migrations.AlterField(
            model_name="groupinteraction",
            name="likee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="projects.group"
            ),
        ),
        migrations.AlterField(
            model_name="groupinteraction",
            name="liker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.student"
            ),
        ),
        migrations.AlterField(
            model_name="interaction",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interactions",
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="interaction",
            name="swipee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="swipee_set",
                to="accounts.student",
            ),
        ),
        migrations.AlterField(
            model_name="interaction",
            name="swiper",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="swiper_set",
                to="accounts.student",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="students",
            field=models.ManyToManyField(
                related_name="joined_projects", to="accounts.student"
            ),
        ),
    ]
