# Generated by Django 4.1.1 on 2022-10-29 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0013_alter_group_candidates_alter_group_members_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.project",
            ),
        ),
    ]
