# Generated by Django 4.1.1 on 2022-11-13 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_auto_20221012_2308"),
        ("projects", "0014_alter_group_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupinteraction",
            name="likee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likee_set",
                to="projects.group",
            ),
        ),
        migrations.AlterField(
            model_name="groupinteraction",
            name="liker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="liker_set",
                to="accounts.student",
            ),
        ),
    ]
